// This file is intentionally left blank.
// The Firebase configuration will be populated by the backend service.
// DO NOT EDIT THIS FILE MANUALLY.
export const firebaseConfig = {
  "projectId": "studio-1148586325-cfc2b",
  "appId": "1:1056997036452:web:9240e9965a573da4057131",
  "apiKey": "AIzaSyCyaGtZ_nI3cKtAKE6wXmN6lMf82VsRUo4",
  "authDomain": "studio-1148586325-cfc2b.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1056997036452"
};
